a = list(map(int, input().split()))
b = list(map(int, input().split()))
set_a = set(a)
set_b = set(b)
print('Различные числа первого списка:', *sorted(set_a))
print('Различные числа второго списка:', *sorted(set_b))
print('Только в первом списке:', *sorted(set_a - set_b))
print('Только во втором списке:', *sorted(set_b - set_a))
print('Различные числа объединения:', *sorted(set_a | set_b))
print('В обоих списках:', *sorted(set_a & set_b))
